// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
using OpenQA.Selenium.DevTools.V125.IndexedDB;
public class SeleniumHomePageTest : IDisposable
{
  public IWebDriver driver { get; private set; }
  public IDictionary<String, Object> vars { get; private set; }
  public IJavaScriptExecutor js { get; private set; }
  public SeleniumHomePageTest()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Testeseleniumhomepage()
  {
    driver.Navigate().GoToUrl("https://www.google.com/");
    driver.FindElement(By.Id("APjFqb")).Click();
    driver.FindElement(By.Id("APjFqb")).SendKeys("Selenium home page");
    driver.FindElement(By.Id("APjFqb")).SendKeys(Keys.Enter);
    driver.FindElement(By.ClassName("yuRUbf")).Click();
  }
}
